name: Deploy Backend

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SOURCE_DIR: "./meetup-frontend/dist"

jobs:
  check-branch:
      runs-on: ubuntu-latest
      steps:
        - name: Ensure merge comes from dev branch
          if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'dev'
          run: |
              echo "Only merges from 'dev' branch are allowed to main!"
              exit 1

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: ./meetup-frontend
        run: npm ci

      - name: Build dist
        working-directory: ./meetup-frontend
        run: npm run build

      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete